### ISSUE TITLE
Recrete The readme file.

### ISSUE THREAD

**Issue by Radhey644** [RealStr1ke/Schedulix#1]
I have carefully reviewed the content and, as a professional writer, I am eager to enhance the readability and user-friendliness of your document. I kindly request the opportunity to contribute to this project during Hacktoberfest. I look forward to collaborating with you.

**Comment by Radhey644** [comment]
@RealStr1ke pls look forward to the concern.

**Comment by RealStr1ke** [comment]
Hello! As of right now, I rewrote the README file and think it looks good for now. Could you make a pull request with the edits you want to make to the README, so we can see how it'll affect readability and user-friendliness? Looking forward to it 😁

**Comment by Radhey644** [comment]
First i would request you to put my work under hactoberfest.
Than I will surely seek under your issue.
and trust me it will be worth it

**Comment by RealStr1ke** [comment]
I just set the topic as hacktoberfest. Do you want me to set this issue as Hacktoberfest?

**Comment by Radhey644** [comment]
Sorry but i dont see the hacktoberfest label here.
