### ISSUE TITLE
Add Contributing.md file

### ISSUE THREAD

**Issue by amitkumar-y** [RealStr1ke/Schedulix#2]
I suggest adding a contributing.md, file to the project. It will have detailed steps which will help new users who want to contribute to this project. You can assign this task to me, and I will create the file.

**Comment by RealStr1ke** [comment]
Go ahead! I just assigned you to it 👍🏽

**Comment by amitkumar-y** [comment]
Hi @RealStr1ke ,
I have added the required file in #4, let me know if it looks good to you are any changes are needed?
